name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  var1: value1


pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    trigger:
      branches:
        - develop
    jobs:
      - job: BuildJob
        steps:
          - script: echo Building!
  - stage: Test
    jobs:
      - job: TestOnWindows
        steps:
          - script: echo Testing on Windows!
      - job: TestOnLinux
        steps:
          - script: echo Testing on Linux!
  - stage: Deploy
    jobs:
      - job: Deploy
        trigger:
          branches:
            - master
        steps:
          - script: echo Deploying the code!