---
exclude_paths:
  - .azuredevops/**
  - .devcontainer/**
  - .github/**
  - .vscode/**
  - dist/**
  - node_modules/**
  - src/specs/**
  - src/tests/**
  - codacy-analysis-cli-master/**
  - '**/config.json'
  - package-lock.json
  - package.json