---
exclude_paths:
  - .azuredevops/**
  - .devcontainer/**
  - .github/**
  - .vscode/**
  - dist/**
  - node_modules/**
  - src/specs/**
  - src/tests/**
  - codacy-analysis-cli-master/**
  - '**/config.json'
  - package-lock.json
  - package.json
  - webpack.common.js
  - webpack.prod.js
  - webpack.dev.js
  - .eslintrc.js
  - jest.config.js