version = 1

test_patterns = ["src/test/**", "src/spec/**"]

exclude_patterns = ["dist/**", "bin/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["jest"]
  plugins = ["vue"]
  style_guide = "standard"
