version: '3.8'

services:
  resume:
    networks:
      - development
    dns:
      - coredns
    container_name: resume
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/resume:cached
    command: sleep infinity
    ports:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`resume.desaules.local`)'
      - 'traefik.http.routers.portainer.entrypoints=web'
      - 'traefik.http.services.portainer.loadbalancer.server.port=3000'

networks:
  development:
    external: true