version: '3.8'

services:
  resume:
    networks:
      - development
    dns:
      - '172.16.254.253'
    container_name: resume
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/resume:cached
    command: sleep infinity
    ports:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.resume.service=resume'
      - 'traefik.http.routers.resume.rule=Host(`resume.desaules.local`)'
      - 'traefik.http.routers.resume.entrypoints=web'
      - 'traefik.http.services.resume.loadbalancer.server.port=3000'

networks:
  development:
    external: true