name: Continuous Integration

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tdesaules'
      - run: npm install
      - run: npm run build:prod
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact-coverage
          path: coverage/*
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact-publish
          path: |
            dist/*
            package.json
          if-no-files-found: error
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact-coverage
      - run: export DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}
      - run: curl https://deepsource.io/cli | sh
      - run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file coverage/cobertura-coverage.xml
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [ "build", "coverage" ]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tdesaules'
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact-publish
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist/*
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}