name: Continuous Integration

on:
  pull_request:
    branches: [master]
    types: [opened]

    jobs:
      build:
        name: build & test
        if: ${{ github.event_name == 'pull_request' && github.head_ref == 'refs/heads/develop' && github.base_ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        steps:
          - id: checkout
            name: checkout repository
            uses: actions/checkout@v2
          - id: setup-node 
            name: setup node software
            uses: actions/setup-node@v1
            with:
              node-version: '12'
              registry-url: 'https://npm.pkg.github.com'
              scope: '@tdesaules'
          - id: install
            name: install npm dependency
            run: npm install
          - id: build
            name: build apps
            run: npm run build:prod
          - id: test
            name: run tests
            run: npm run test
          - id: install-deepsource
            name: install deepsource cli
            run: curl https://deepsource.io/cli | sh
          - id: deepsource-coverage
            name: deepsource upload code & coverage
            run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file coverage/cobertura-coverage.xml
            env:
              DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
          - id: artifact
            name: upload artifact
            uses: actions/upload-artifact@v2
            with:
              name: my-artifact-coverage
              path: |
                dits/*
                coverage/*
              if-no-files-found: error
          - id: package
            name: publish package
            run: npm publish
            env:
              NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}