name: CI / CD

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  continuous-integration :
    name: Continuous Integration
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tdesaules'
      - run: npm install
      - run: npm run build:prod
      - uses: actions/upload-artifact@v2
        with:
          path: dist/
          if-no-files-found: error
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  continuous-deployment-develop:
    name: Continuous Delivery Develop
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm run build:dev
      - run: npm install --global vercel
      - run: mkdir .vercel
      - run: echo '{"orgId":"Yv1xc0fvIE4ZoGxCVlrFxJqj","projectId":"QmbBDxnqzjsRWmYcgxG4UBzF2HRx1GdzYxEN45aFjcnnXU"}' > .vercel/project.json
      - run: vercel --token YrCkNGR5dnpTJUFpLZfu3HcW --prod --confirm
  continuous-deployment-master:
    name: Continuous Delivery Master
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tdesaules'
      - run: npm install @tdesaules/resume
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mv node_modules/@tdesaules/resume/dist .
      - run: npm install --global vercel
      - run: mkdir .vercel
      - run: echo '{"orgId":"Yv1xc0fvIE4ZoGxCVlrFxJqj","projectId":"QmPuUbvg2iyXAk4MTbm5bLxrx96j9ui7HvSk74x9Ds2Dr7"}' > .vercel/project.json
      - run: vercel --token YrCkNGR5dnpTJUFpLZfu3HcW --prod --confirm