name: CI Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build:dev