name: CI

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  ci:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tdesaules'
      - run: npm install
      - run: npm run build:prod
      - uses: actions/upload-artifact@v2
        with:
          path: dist/
          if-no-files-found: error
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}