name: Deploy

on:
  release:
    types: [released]

jobs:
  deploy:
    name: Deploy release
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tdesaules'
      - name: Install npm resume package
        run: |
          TAG=$(echo $GITHUB_REF | sed 's/.*\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\).*/\1/g')
          npm install @tdesaules/resume@$TAG
          mv node_modules/@tdesaules/resume/dist .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Vercel
        run: |
          npm install --global vercel
          mkdir .vercel && echo '{"orgId":"${{ secrets.VERCEL_ORGID }}","projectId":"${{ secrets.VERCEL_PROJECTID_PRD }}"}' > .vercel/project.json
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm