name: Development

on:
  push:
    branches: [ develop ]

jobs:
  release-develop:
    name: Deploy Development
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - name: Build
        run: |
          npm install
          npm run build:dev
      - name: Deploy to vercel dev project
        run: |
          npm install --global vercel
          mkdir .vercel
          echo '{"orgId":"${{ secrets.VERCEL_ORGID }}","projectId":"${{ secrets.VERCEL_PROJECTID_DEV }}"}' > .vercel/project.json
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
