name: ShiftLeft

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  codeql:
    name: CodeQL Analyze
    if: ${{ github.event_name == 'pull_request' && github.head_ref == 'develop' && github.base_ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Download ShiftLeft
        run: mkdir bin && curl https://cdn.shiftleft.io/download/sl > bin/sl && chmod a+rx bin/sl
      - name: Auth ShiftLeft
        run: bin/sl auth --org "${{ secrets.SHIFTLEFT_ORG }}" --token "${{ secrets.SHIFTLEFT_TOKEN }}" --diagnostic
      - name: ShiftLeft Analyze
        run: bin/sl analyze --app "resume" --cpg --js .